# itens_neurociencia.py

# 🔹 Questionário Sociodemográfico
SOCIODEMOGRAFICO = [
    "Qual é o seu gênero?",
    "Quantos anos você tem?",
    "Você mora em qual região do país?",
    "Qual é a renda do seu núcleo familiar, em relação ao salário mínimo?",
    "Qual é o seu nível de escolaridade?",
    "Quantos filhos você tem?",
    "Você ou algum familiar seu já foi diagnosticado com TEA?",
    "Você já precisou de acompanhamento psiquiátrico?",
    "Você abusa de alguma substância psicoativa (maconha, álcool, cigarro etc.)?",
]

# 🔹 LPFS-BF – Níveis de Funcionamento da Personalidade (versão brasileira validada)
LPFS_BF = [
    "Eu frequentemente não sei quem sou.",
    "Eu frequentemente tenho pensamentos muito negativos sobre mim mesmo.",
    "Minhas emoções mudam sem que eu tenha controle sobre elas.",
    "Eu não tenho ideia de onde quero chegar em minha vida.",
    "Eu frequentemente não entendo meus próprios pensamentos e sentimentos.",
    "Eu frequentemente faço exigências irrealistas para mim mesmo.",
    "Eu frequentemente tenho dificuldade de entender os pensamentos e sentimentos dos outros.",
    "Eu frequentemente tenho dificuldade de tolerar quando os outros discordam de mim.",
    "Eu frequentemente não entendo totalmente por que meu comportamento tem um determinado efeito sobre os outros.",
    "Meus relacionamentos e amizades nunca duram por muito tempo.",
    "Eu frequentemente me sinto inseguro quando minhas relações se tornam mais íntimas.",
    "Eu frequentemente não consigo cooperar com os outros de modo que seja satisfatório tanto para mim quanto para os outros.",
]


# 🔹 LSM– Facetas de Mindfulness
LSM = [
    "Eu gosto de investigar sobre qualquer coisa.",
    "Eu produzo poucas ideias novas.",
    "Eu estou sempre aberto(a) a novas maneiras de fazer as coisas.",
    "Eu me envolvo em quase tudo que faço.",
    "Eu não procuro ativamente aprender coisas novas.",
    "Eu faço muitas contribuições inovadoras.",
    "Eu prefiro o jeito habitual e conhecido de fazer as coisas",
    "Eu raramente noto o que as outras pessoas estão fazendo.",
    "Eu evito conversas que provocam reflexões.",
    "Eu sou muito criativo(a).",
    "Eu consigo me comportar de várias formas diferentes em uma mesma situação.",
    "Eu ligo com a situação como \"um todo\".",
    "Eu sou muito curioso(a).",
    "Eu tento pensar em novas maneiras de fazer as coisas.",
    "Eu raramente estou ciente das mudanças.",
    "Eu tenho uma mente aberta para tudo, até mesmo para coisas que desafiam minhas crenças mais importantes.",
    "Eu gosto de ser desafiado(a) intelectualmente.",
    "Eu acho fácil criar ideias novas e efetivas.",
    "Eu raramente estou alerta aos novos acontecimentos das coisas ao meu redor.",
    "Eu gosto de descobrir como as coisas funcionam.",
    "Eu não sou uma pessoa que tem pensamentos originais."
]

# 🔹 PID-5-BF – Inventário Breve de Personalidade do DSM-5
PID_5_BF = [
    "As pessoas me descreveriam como impulsivo(a).",
    "Sinto que ajo totalmente por impulso.",
    "Mesmo sabendo que estou errado(a), não consigo parar de tomar decisões precipitadas.",
    "Frequentemente sinto que nada do que eu faço realmente importa.",
    "Os outros me veem como irresponsável.",
    "Não sou bom/boa em planejar com antecedência.",
    "Meus pensamentos frequentemente não fazem sentido para os outros.",
    "Me preocupo com quase tudo.",
    "Fico emocional com facilidade, muitas vezes por pouca coisa.",
    "Tenho mais medo de ficar sozinho(a) na vida do que de qualquer outra coisa.",
    "Fico preso(a) em uma forma de fazer as coisas, mesmo quando está claro que não funciona.",
    "Já vi coisas que não estavam realmente lá.",
    "Evito relacionamentos românticos.",
    "Não tenho interesse em fazer amizades.",
    "Fico irritado(a) facilmente com todo tipo de coisa.",
    "Não gosto de me aproximar demais das pessoas.",
    "Não é grande coisa se eu magoar os sentimentos dos outros.",
    "Raramente fico entusiasmado(a) com qualquer coisa.",
    "Sinto necessidade de atenção.",
    "Frequentemente tenho que lidar com pessoas menos importantes do que eu.",
    "Frequentemente tenho pensamentos que fazem sentido para mim, mas que outras pessoas acham estranhos.",
    "Uso as pessoas para conseguir o que quero.",
    "Frequentemente 'desligo' e de repente percebo que muito tempo se passou.",
    "As coisas ao meu redor frequentemente parecem irreais, ou mais reais do que o normal.",
    "É fácil para mim tirar vantagem dos outros.",
]

# 🔹 AQ-50 – Quociente do Espectro Autista (versão completa e validada)
AQ_50 = [
    "Prefiro fazer coisas com outras pessoas do que sozinho(a).",
    "Prefiro fazer as coisas sempre da mesma maneira.",
    "Quando tento imaginar uma coisa, tenho muita facilidade em criar uma imagem na minha mente.",
    "Com frequência fico tão absorvido(a) com uma coisa que esqueço todo o resto.",
    "Frequentemente noto pequenos ruídos que outras pessoas não ouvem.",
    "Costumo prestar atenção aos números das placas dos automóveis ou a outras sequências de informação do mesmo tipo.",
    "As outras pessoas com frequência me dizem que falei algo indelicado, apesar de eu achar que fui delicado(a).",
    "Quando leio uma história, consigo imaginar facilmente a aparência dos personagens.",
    "Sou fascinado por datas.",
    "Quando estou em grupo, tenho facilidade em seguir várias conversas ao mesmo tempo.",
    "Tenho facilidade em compreender situações sociais.",
    "Tenho tendência a notar detalhes que os outros não reparam.",
    "Prefiro ir a uma biblioteca do que a uma festa.",
    "Tenho facilidade em inventar histórias.",
    "Tenho maior tendência a me aproximar de pessoas do que de coisas.",
    "Tenho tendência a ter interesses fortes e fico incomodado(a) se não posso me dedicar a eles.",
    "Gosto de bater papo.",
    "Quando estou falando, as outras pessoas têm dificuldade em tomar a palavra.",
    "Os números me fascinam.",
    "Quando leio uma história, sinto dificuldade em entender as intenções dos personagens.",
    "Não aprecio ler livros de ficção.",
    "Tenho dificuldade em fazer novos amigos.",
    "Vejo constantemente padrões nas coisas que me rodeiam.",
    "Prefiro ir ao teatro do que ir a um museu.",
    "Não fico incomodado(a) se minha rotina diária for alterada.",
    "Com frequência sinto que não sei manter uma conversa.",
    "Tenho facilidade em “ler nas entrelinhas” quando falam comigo.",
    "Geralmente me concentro mais no todo do que nos detalhes.",
    "Não sou muito bom/boa em lembrar números de telefone.",
    "Geralmente não reparo nas pequenas mudanças de uma situação ou na aparência de uma pessoa.",
    "Consigo dizer quando a pessoa com quem estou conversando fica entediada.",
    "Consigo facilmente fazer mais do que uma coisa ao mesmo tempo.",
    "Quando falo no telefone, não tenho a certeza quando é a minha vez de falar.",
    "Gosto de fazer as coisas de forma espontânea.",
    "Com frequência sou o(a) último(a) que entende uma piada.",
    "Tenho facilidade em entender o que uma pessoa está pensando ou sentindo apenas olhando para o seu rosto.",
    "Se sou interrompido(a), consigo rapidamente voltar ao que estava fazendo.",
    "Sou bom/boa de papo.",
    "Os outros frequentemente me dizem que eu insisto muito nas mesmas coisas.",
    "Quando era criança, gostava de brincar de faz-de-conta com as outras crianças.",
    "Gosto de colecionar informação sobre categorias de coisas (p. ex., tipos de carros, de aves, de trens, de plantas, etc.).",
    "Tenho dificuldade de me imaginar na pele de outra pessoa.",
    "Gosto de planejar com cuidado todas as atividades em que participo.",
    "Aprecio eventos sociais.",
    "Tenho dificuldade em entender as intenções das outras pessoas.",
    "Situações novas me deixam ansioso(a).",
    "Gosto de conhecer pessoas novas.",
    "Tenho uma postura conciliadora em situações de interação social.",
    "Tenho dificuldade para lembrar o aniversário das pessoas.",
    "Tenho muita facilidade em brincar de faz-de-conta com as crianças."
]

