# itens_neurociencia.py

# 🔹 Questionário Sociodemográfico
SOCIODEMOGRAFICO = [
    "Qual é o seu gênero?",
    "Quantos anos você tem?",
    "Você mora em qual região do país?",
    "Qual é a renda do seu núcleo familiar, em relação ao salário mínimo?",
    "Qual é o seu nível de escolaridade?",
    "Quantos filhos você tem?",
    "Você ou algum familiar seu já foi diagnosticado com TEA?",
    "Você já precisou de acompanhamento psiquiátrico?",
    "Você abusa de alguma substância psicoativa (maconha, álcool, cigarro etc.)?",
]

# 🔹 LPFS-BF – Níveis de Funcionamento da Personalidade (versão brasileira validada)
LPFS_BF = [
    "Eu frequentemente não sei quem sou.",
    "Eu frequentemente tenho pensamentos muito negativos sobre mim mesmo.",
    "Minhas emoções mudam sem que eu tenha controle sobre elas.",
    "Eu não tenho ideia de onde quero chegar em minha vida.",
    "Eu frequentemente não entendo meus próprios pensamentos e sentimentos.",
    "Eu frequentemente faço exigências irrealistas para mim mesmo.",
    "Eu frequentemente tenho dificuldade de entender os pensamentos e sentimentos dos outros.",
    "Eu frequentemente tenho dificuldade de tolerar quando os outros discordam de mim.",
    "Eu frequentemente não entendo totalmente por que meu comportamento tem um determinado efeito sobre os outros.",
    "Meus relacionamentos e amizades nunca duram por muito tempo.",
    "Eu frequentemente me sinto inseguro quando minhas relações se tornam mais íntimas.",
    "Eu frequentemente não consigo cooperar com os outros de modo que seja satisfatório tanto para mim quanto para os outros.",
]


# 🔹 CFQ – Questionário de Falhas Cognitivas
CFQ = [
    "Você lê alguma coisa, percebe que não estava prestando atenção e precisa lê-la novamente?",
    "Você se esquece por que foi de um cômodo a outro dentro de casa?",
    "Você deixa de notar placas de sinalização ao dirigir?",
    "Você confunde esquerda e direita ao indicar o caminho a alguém?",
    "Você esbarra (“tromba”) em outras pessoas?",
    "Você esquece se apagou a luz, a chama do fogão ou se trancou a porta?",
    "Você não se atenta ao nome da pessoa quando ela está sendo apresentada a você?",
    "Você diz alguma coisa e depois percebe que isso pode ter sido interpretado como um insulto?",
    "Você tem dificuldade em escutar as pessoas falando com você quando está fazendo outra coisa?",
    "Você perde a calma e se arrepende?",
    "Você deixa cartas, mensagens ou e-mails importantes sem resposta por dias?",
    "Você esquece aonde virar em um caminho que conhece bem, mas usa pouco?",
    "Você tem dificuldades em achar o que você quer no supermercado, embora o produto esteja por lá?",
    "Você se encontra subitamente pensando se usou uma palavra de forma correta?",
    "Você tem problemas em se decidir?",
    "Você esquece os seus compromissos?",
    "Você esquece onde colocou alguma coisa, como o jornal, o celular ou suas chaves?",
    "Você acidentalmente joga fora algo que queria guardar e fica com aquilo que queria descartar (por exemplo, joga fora uma bala e guarda seu papel no bolso)?",
    "Você “viaja” ou fica “no mundo da lua” quando deveria estar ouvindo alguma coisa?",
    "Você esquece o nome das pessoas?",
    "Você começa a fazer alguma coisa em casa e se distrai fazendo algo diferente (sem querer)?",
    "Você não consegue se lembrar de alguma coisa, mesmo que esteja “na ponta da língua”?",
    "Você se esquece do que saiu para comprar?",
    "Você deixa as coisas caírem (as derruba)?",
    "Você não consegue pensar em nada para dizer?",
]

# 🔹 PID-5-BF – Inventário Breve de Personalidade do DSM-5
PID_5_BF = [
    "As pessoas me descreveriam como imprudente.",
    "Eu sinto que ajo totalmente por impulso.",
    "Mesmo sabendo que não é o melhor, eu não consigo parar de tomar decisões precipitadas.",
    "Eu frequentemente sinto que nada que faço realmente importa.",
    "Os outros me veem como irresponsável.",
    "Eu não sou bom (boa) em planejar as coisas com antecedência.",
    "Meus pensamentos frequentemente não fazem sentido para os outros.",
    "Eu me preocupo com quase tudo.",
    "Eu me emociono facilmente, muitas vezes por pequenas razões.",
    "Eu tenho medo de ficar sozinho (a) na vida mais do que qualquer outra coisa.",
    "Eu fico preso (a) a um jeito de fazer as coisas, mesmo quando está claro que não vai dar certo.",
    "Eu tenho visto coisas que na realidade não estavam lá.",
    "Eu evito relacionamentos amorosos.",
    "Eu não tenho interesse em fazer amigos.",
    "Eu fico irritado (a) facilmente por qualquer tipo de coisa.",
    "Eu não gosto de ficar muito perto das pessoas.",
    "Não me parece grande coisa se eu ferir os sentimentos das outras pessoas.",
    "Eu raramente me entusiasmo com alguma coisa.",
    "Eu preciso muito de atenção.",
    "Eu frequentemente tenho que lidar com pessoas que são menos importantes que eu.",
    "Eu frequentemente tenho pensamentos que fazem sentido para mim, mas que outras pessoas dizem que são estranhos.",
    "Eu uso as pessoas para conseguir o que eu quero.",
    "Eu frequentemente “fico desligado (a)” e de repente volto a mim e percebo que passou bastante tempo.",
    "As coisas ao meu redor frequentemente parecem irreais ou mais reais do que o habitual.",
    "É fácil para mim tirar proveito dos outros."
]


# 🔹 AQ-50 – Quociente do Espectro Autista (versão completa e validada)
AQ_50 = [
    "Prefiro fazer coisas com outras pessoas do que sozinho(a).",
    "Prefiro fazer as coisas sempre da mesma maneira.",
    "Quando tento imaginar uma coisa, tenho muita facilidade em criar uma imagem na minha mente.",
    "Com frequência fico tão absorvido(a) com uma coisa que esqueço todo o resto.",
    "Frequentemente noto pequenos ruídos que outras pessoas não ouvem.",
    "Costumo prestar atenção aos números das placas dos automóveis ou a outras sequências de informação do mesmo tipo.",
    "As outras pessoas com frequência me dizem que falei algo indelicado, apesar de eu achar que fui delicado(a).",
    "Quando leio uma história, consigo imaginar facilmente a aparência dos personagens.",
    "Sou fascinado por datas.",
    "Quando estou em grupo, tenho facilidade em seguir várias conversas ao mesmo tempo.",
    "Tenho facilidade em compreender situações sociais.",
    "Tenho tendência a notar detalhes que os outros não reparam.",
    "Prefiro ir a uma biblioteca do que a uma festa.",
    "Tenho facilidade em inventar histórias.",
    "Tenho maior tendência a me aproximar de pessoas do que de coisas.",
    "Tenho tendência a ter interesses fortes e fico incomodado(a) se não posso me dedicar a eles.",
    "Gosto de bater papo.",
    "Quando estou falando, as outras pessoas têm dificuldade em tomar a palavra.",
    "Os números me fascinam.",
    "Quando leio uma história, sinto dificuldade em entender as intenções dos personagens.",
    "Não aprecio ler livros de ficção.",
    "Tenho dificuldade em fazer novos amigos.",
    "Vejo constantemente padrões nas coisas que me rodeiam.",
    "Prefiro ir ao teatro do que ir a um museu.",
    "Não fico incomodado(a) se minha rotina diária for alterada.",
    "Com frequência sinto que não sei manter uma conversa.",
    "Tenho facilidade em “ler nas entrelinhas” quando falam comigo.",
    "Geralmente me concentro mais no todo do que nos detalhes.",
    "Não sou muito bom/boa em lembrar números de telefone.",
    "Geralmente não reparo nas pequenas mudanças de uma situação ou na aparência de uma pessoa.",
    "Consigo dizer quando a pessoa com quem estou conversando fica entediada.",
    "Consigo facilmente fazer mais do que uma coisa ao mesmo tempo.",
    "Quando falo no telefone, não tenho a certeza quando é a minha vez de falar.",
    "Gosto de fazer as coisas de forma espontânea.",
    "Com frequência sou o(a) último(a) que entende uma piada.",
    "Tenho facilidade em entender o que uma pessoa está pensando ou sentindo apenas olhando para o seu rosto.",
    "Se sou interrompido(a), consigo rapidamente voltar ao que estava fazendo.",
    "Sou bom/boa de papo.",
    "Os outros frequentemente me dizem que eu insisto muito nas mesmas coisas.",
    "Quando era criança, gostava de brincar de faz-de-conta com as outras crianças.",
    "Gosto de colecionar informação sobre categorias de coisas (p. ex., tipos de carros, de aves, de trens, de plantas, etc.).",
    "Tenho dificuldade de me imaginar na pele de outra pessoa.",
    "Gosto de planejar com cuidado todas as atividades em que participo.",
    "Aprecio eventos sociais.",
    "Tenho dificuldade em entender as intenções das outras pessoas.",
    "Situações novas me deixam ansioso(a).",
    "Gosto de conhecer pessoas novas.",
    "Tenho uma postura conciliadora em situações de interação social.",
    "Tenho dificuldade para lembrar o aniversário das pessoas.",
    "Tenho muita facilidade em brincar de faz-de-conta com as crianças."
]

