SUPABASE_URL = "https://vgmgiphpewvjhyfdybyd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnbWdpcGhwZXd2amh5ZmR5YnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjczMTYsImV4cCI6MjA1NzIwMzMxNn0.AQ7bxKSYaET9PMYkVQ3lcW2eeN5fuJeAFfuNdQkVql8"
LOCAL_DEBUG = "true"